### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by StevenHermans** [simoneluconi/AurorapyToMqtt#5]
Hi, where can I find the depending AuroraError and AuroraTCPClient?

I get "ModuleNotFoundError: No module named 'aurorapy'" when trying to run the solution.

I'm not an expert in this...

**Comment by simoneluconi** [comment]
You need to install it with the command
`pip install aurorapy`

**Comment by StevenHermans** [comment]
My pip doesn't seem to work but I found all elements in the meantime. Inverter is down for the moment so I'll check again next days. Does the script have to run periodically or just run it once?

**Comment by simoneluconi** [comment]
Just need to run it once, it will start to report data when the inverter comes back online

**Comment by StevenHermans** [comment]
I got somewhat further: I got passed the MQQT connection but now, it seems I can't connect to the Inverter.
![2024-10-03 10_33_49-raspberrypi home (pi)](https://github.com/user-attachments/assets/a9d273be-119e-41a5-8278-96073ada566a)
Message:
"Connected with result code 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aurorapy-0.2.7-py3.11.egg/aurorapy/client.py", line 623, in connect
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/qbtools-v3/AuroraComm.py", line 23, in <module>
    c.connect()
  File "/usr/local/lib/python3.11/dist-packages/aurorapy-0.2.7-py3.11.egg/aurorapy/client.py", line 626, in connect
aurorapy.client.AuroraError: [Errno 111] Connection refused"

I can connect to the web-portal of the Inverter through the same IP address. I logon using a user id and password.
L22: c = AuroraTCPClient(ip='192.168.1.64', port=8899, address=2)
L23: c.connect()

Could it be the port? Any idea on how to get connected?

**Comment by simoneluconi** [comment]
Yes probably is the wrong port, you have to check in web portal of your converter which is the port that accecpt tcp connections.

**Comment by StevenHermans** [comment]
Found the correct port I assume:
c = AuroraTCPClient(ip='192.168.1.64', port=502, address=10)

No error anymore but nothing is happening...
I get "Connected with result code 0' but then nothing..
![image](https://github.com/user-attachments/assets/125d55e1-9778-4e8e-b5a7-edb6b8ed818a)

When I do a different test with
"from aurorapy.client import AuroraError, AuroraTCPClient # or AuroraSerialClient
client = AuroraTCPClient(ip='192.168.1.64', port=502, address=10)
client.connect()
try:
  print("Inverter serial number: %s" % client.serial_number())
except AuroraError as e:
  print(e.message)
client.close()"

Nothing happening either and I get this:
![image](https://github.com/user-attachments/assets/f588f60c-d148-4896-9b60-2ecd1134b205)

Any idea? Still the wrong port now?

**Comment by simoneluconi** [comment]
If you don't get anything it means that is not communicating with the inverter.

I think that at this point could be or an incorrect configuration of the serial port parameter, check in the converter that they are:
`baudrate=19200, parity='N', stop_bits=1, data_bits=8`
if they are correct could be a incorrect wiring of the serial cable.

**Comment by StevenHermans** [comment]
Is this what you are referring too?
![image](https://github.com/user-attachments/assets/6f8fe206-090e-4028-b5fa-168e41c8219f)
for the protocol: it is on 'Modbus SunSpec Server' (I don't find the data bits)

**Comment by simoneluconi** [comment]
mmh i don't know whitch converter are you using, but definitely it shouldn't be modbus. try setting it on aurora server, if i still not working you should try with any cheap tcp to rs485 converter.

**Comment by StevenHermans** [comment]
I got it working but through another library...this one: https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec
with the parms 
![image](https://github.com/user-attachments/assets/8f90a5a6-c63a-4ac3-9204-05ee21cbdcdc)

Tried the same parms on your library but didn't get it working. Thanks for your fast replies!!

**Comment by simoneluconi** [comment]
i think this library is for a different model of inverter than mine.
